//
// File:         GematogenDebugFlags.hpp
// Description:  Debugging flags for the Gematogen library
// Created:      Jan 26, 2001, 10:00
// Author:       Alexandre Riazanov
// mail:         riazanov@cs.man.ac.uk
//=================================================================== 
#include "BlodKorvDebugFlags.hpp"
//=================================================================== 

#ifdef NO_DEBUG
 #undef NO_DEBUG_VIS
 #define NO_DEBUG_VIS
#endif
//#define DEBUG_BACKWARD_SUBSUMPTION_WITH_PATH_INDEXING_AND_JOINS
//#define DEBUG_STANDARD_PATH_INDEXING_WITH_COMPILED_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
//#define DEBUG_FORWARD_MATCHING_INDEX
//#define DEBUG_FORWARD_MATCHING_INDEX_PLUS
//#define DEBUG_FORWARD_MATCHING_INDEX_PLUS_TREE
//#define DEBUG_FORWARD_MATCHING_INDEX_TREE
//#define DEBUG_INSTANCE_RETRIEVAL_FROM_DISC_TREE
//#define DEBUG_PATH_INDEXING_WITH_JOINS_FOR_INSTANCE_RETRIEVAL
//#define DEBUG_PATH_INDEXING_WITH_JOINS_AND_EARLY_AND_COMPILED_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
//#define DEBUG_PATH_INDEXING_WITH_JOINS_AND_EARLY_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
//#define DEBUG_INSTANCE_RETRIEVAL_WITH_PATH_INDEX
//#define DEBUG_STANDARD_PATH_INDEXING_FOR_INSTANCE_RETRIEVAL
//#define DEBUG_PATH_INDEX
//#define DEBUG_PATH_INDEX_WITH_OPEN_PATHS
//#define DEBUG_PATH_INDEX_FOR_BACKWARD_SUBSUMPTION
//#define DEBUG_PATH_PROBE_INDEX

#ifdef NO_DEBUG
 #undef DEBUG_BACKWARD_SUBSUMPTION_WITH_PATH_INDEXING_AND_JOINS
 #undef DEBUG_STANDARD_PATH_INDEXING_WITH_COMPILED_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
 #undef DEBUG_FORWARD_MATCHING_INDEX
 #undef DEBUG_FORWARD_MATCHING_INDEX_PLUS
 #undef DEBUG_FORWARD_MATCHING_INDEX_PLUS_TREE
 #undef DEBUG_FORWARD_MATCHING_INDEX_TREE
 #undef DEBUG_INSTANCE_RETRIEVAL_FROM_DISC_TREE
 #undef DEBUG_PATH_INDEXING_WITH_JOINS_FOR_INSTANCE_RETRIEVAL
 #undef DEBUG_PATH_INDEXING_WITH_JOINS_AND_EARLY_AND_COMPILED_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
 #undef DEBUG_PATH_INDEXING_WITH_JOINS_AND_EARLY_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
 #undef DEBUG_INSTANCE_RETRIEVAL_WITH_PATH_INDEX
 #undef DEBUG_STANDARD_PATH_INDEXING_FOR_INSTANCE_RETRIEVAL
 #undef DEBUG_PATH_INDEX
 #undef DEBUG_PATH_INDEX_WITH_OPEN_PATHS 
 #undef DEBUG_PATH_INDEX_FOR_BACKWARD_SUBSUMPTION
 #undef DEBUG_PATH_PROBE_INDEX 
#else
 #ifdef DEBUG_ALL
  #define DEBUG_BACKWARD_SUBSUMPTION_WITH_PATH_INDEXING_AND_JOINS
  #define DEBUG_STANDARD_PATH_INDEXING_WITH_COMPILED_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
  #define DEBUG_FORWARD_MATCHING_INDEX
  #define DEBUG_FORWARD_MATCHING_INDEX_PLUS
  #define DEBUG_FORWARD_MATCHING_INDEX_PLUS_TREE
  #define DEBUG_FORWARD_MATCHING_INDEX_TREE
  #define DEBUG_INSTANCE_RETRIEVAL_FROM_DISC_TREE
  #define DEBUG_PATH_INDEXING_WITH_JOINS_FOR_INSTANCE_RETRIEVAL
  #define DEBUG_PATH_INDEXING_WITH_JOINS_AND_EARLY_AND_COMPILED_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
  #define DEBUG_PATH_INDEXING_WITH_JOINS_AND_EARLY_CLEAN_UP_FOR_INSTANCE_RETRIEVAL
  #define DEBUG_INSTANCE_RETRIEVAL_WITH_PATH_INDEX
  #define DEBUG_STANDARD_PATH_INDEXING_FOR_INSTANCE_RETRIEVAL
  #define DEBUG_PATH_INDEX
  #define DEBUG_PATH_INDEX_WITH_OPEN_PATHS
  #define DEBUG_PATH_INDEX_FOR_BACKWARD_SUBSUMPTION
  #define DEBUG_PATH_PROBE_INDEX
 #endif
#endif


//==========================================================================

